# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Player settings
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_VELOCITY = 10
PLAYER_SHOT_DELAY = 0.1 #100ms

# Enemy settings
ENEMY_WIDTH = 50
ENEMY_HEIGHT = 50
ENEMY_MIN_VELOCITY = 1
ENEMY_MAX_VELOCITY = 3
ENEMY_SHOT_PROBABILITY = 10 # value between 0 and 1000

# Game settings
GAME_FPS = 60

# Projectile settings
PROJECTILE_ENEMY_WIDTH = 5
PROJECTILE_ENEMY_HEIGHT = 10
PROJECTILE_PLAYER_WIDTH = 10
PROJECTILE_PLAYER_HEIGHT = 20
PROJECTILE_PLAYER_VELOCITY = 10
PROJECTILE_ENEMY_VELOCITY = 1
