# Screen settings
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800

# Player settings
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_VELOCITY = 10
PLAYER_SHOOT_DELAY = 0.1 #100ms

# Enemy settings
ENEMY_WIDTH = 50
ENEMY_HEIGHT = 50
ENEMY_VELOCITY = 2
ENEMY_SHOOT_PROBABILITY = 10 # value between 0 and 1000
ENEMY_COUNT = 5

# Super enemy settings
SUPER_ENEMY_WIDTH = 100
SUPER_ENEMY_HEIGHT = 100
SUPER_ENEMY_VELOCITY = 1
SUPER_ENEMY_SHOOT_PROBABILITY = 20 # value between 0 and 1000
SUPER_ENEMY_LIVES = 5

# Game settings
GAME_FPS = 60

# Projectile settings
PROJECTILE_ENEMY_WIDTH = 5
PROJECTILE_ENEMY_HEIGHT = 10
PROJECTILE_PLAYER_WIDTH = 10
PROJECTILE_PLAYER_HEIGHT = 20
PROJECTILE_PLAYER_VELOCITY = 10
PROJECTILE_ENEMY_VELOCITY = 1
PROJECTILE_THIGH_VELOCITY = 3
PROJECTILE_THIGH_WIDTH = 10
PROJECTILE_THIGH_HEIGHT = 10