# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Player settings
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_VELOCITY = 20
PLAYER_SHOT_DELAY = 0.1 #100ms

# Enemy settings
ENEMY_WIDTH = 50
ENEMY_HEIGHT = 50
ENEMY_MIN_VELOCITY = 1
ENEMY_MAX_VELOCITY = 3

# Game settings
GAME_FPS = 60

# Projectile settings
PROJECTILE_WIDTH = 5
PROJECTILE_HEIGHT = 10
PROJECTILE_VELOCITY = 10
